import { encodeCharacter } from './encoding';
import type { ProjectData } from './projectModel';
import { validateProject } from './validation';

export function exportCharsetBinary(project: ProjectData): Uint8Array {
  const output = new Uint8Array(256 * 8);
  project.characters.forEach((char, index) => {
    output.set(encodeCharacter(char.pixels), index * 8);
  });
  return output;
}

export function exportCharacterVisibleColours(project: ProjectData): Uint8Array {
  return new Uint8Array(project.characters.map((char) => char.defaultVisibleColor));
}

export function exportCharacterColourRamBytes(project: ProjectData): Uint8Array {
  return new Uint8Array(project.characters.map((char) => char.defaultVisibleColor + 8));
}

export function exportTilesFlat(project: ProjectData): Uint8Array {
  return new Uint8Array(project.tiles.flatMap((tile) => tile.characterIndexes));
}

export function exportTilesSeparated(project: ProjectData): Record<string, Uint8Array> {
  const files: Record<string, Uint8Array> = {};
  for (let y = 0; y < project.tileHeight; y += 1) {
    for (let x = 0; x < project.tileWidth; x += 1) {
      const name = `tile_x${x}_y${y}.bin`;
      const out = new Uint8Array(256);
      for (let tileIndex = 0; tileIndex < 256; tileIndex += 1) {
        out[tileIndex] = project.tiles[tileIndex].characterIndexes[y * project.tileWidth + x];
      }
      files[name] = out;
    }
  }
  return files;
}

export function exportProjectJson(project: ProjectData): string {
  return JSON.stringify(project, null, 2);
}

export function importProjectJson(jsonText: string): ProjectData {
  const parsed = JSON.parse(jsonText) as ProjectData;
  const validationErrors = validateProject(parsed);
  if (validationErrors.length > 0) {
    throw new Error(`Invalid project JSON:\n${validationErrors.join('\n')}`);
  }
  return parsed;
}

function toHexRows(data: Uint8Array, columns = 16): string {
  const lines: string[] = [];
  for (let i = 0; i < data.length; i += columns) {
    lines.push(
      Array.from(data.slice(i, i + columns))
        .map((value) => `0x${value.toString(16).padStart(2, '0')}`)
        .join(', '),
    );
  }
  return lines.join(',\n  ');
}

export function exportOscar64C(project: ProjectData): string {
  const charset = exportCharsetBinary(project);
  const visible = exportCharacterVisibleColours(project);
  const colorRam = exportCharacterColourRamBytes(project);
  const tilesFlat = exportTilesFlat(project);
  const planes = exportTilesSeparated(project);

  const lines: string[] = [
    '// Generated by C64 VIC-II Multicolour Charset Editor',
    `// tile size: ${project.tileWidth}x${project.tileHeight}`,
    '',
    `unsigned char charsetData[${charset.length}] = { // length: ${charset.length}`,
    `  ${toHexRows(charset)}`,
    '};',
    '',
    `unsigned char characterVisibleColours[${visible.length}] = { // length: ${visible.length}`,
    `  ${toHexRows(visible)}`,
    '};',
    '',
    `unsigned char characterColourRamBytes[${colorRam.length}] = { // length: ${colorRam.length}`,
    `  ${toHexRows(colorRam)}`,
    '};',
    '',
    `unsigned char tileMapFlat[${tilesFlat.length}] = { // length: ${tilesFlat.length}`,
    `  ${toHexRows(tilesFlat)}`,
    '};',
    '',
  ];

  Object.entries(planes).forEach(([name, data]) => {
    const arrayName = name.replace('.bin', '').replace(/[^a-zA-Z0-9_]/g, '_');
    lines.push(`unsigned char ${arrayName}[${data.length}] = { // length: ${data.length}`);
    lines.push(`  ${toHexRows(data)}`);
    lines.push('};');
    lines.push('');
  });

  return lines.join('\n');
}

export function assertProjectForExport(project: ProjectData): void {
  const validationErrors = validateProject(project);
  if (validationErrors.length > 0) {
    throw new Error(`Project validation failed:\n${validationErrors.join('\n')}`);
  }
}
