import { exportCharsetBinary } from './encoding';
import {
  CHARACTER_COUNT,
  TILE_COUNT,
  type ProjectData,
} from './projectModel';

export interface NamedBinaryExport {
  filename: string;
  bytes: Uint8Array;
}

export function exportCharacterVisibleColours(project: ProjectData): Uint8Array {
  return Uint8Array.from(project.characters.map((character) => character.defaultVisibleColor));
}

export function exportCharacterColourRamBytes(project: ProjectData): Uint8Array {
  return Uint8Array.from(project.characters.map((character) => character.defaultVisibleColor + 8));
}

export function exportTilesFlat(project: ProjectData): Uint8Array {
  return Uint8Array.from(project.tiles.flatMap((tile) => tile.characterIndexes));
}

export function exportTilesSeparated(project: ProjectData): NamedBinaryExport[] {
  const files: NamedBinaryExport[] = [];
  for (let y = 0; y < project.tileHeight; y += 1) {
    for (let x = 0; x < project.tileWidth; x += 1) {
      const offset = y * project.tileWidth + x;
      files.push({
        filename: `tile_x${x}_y${y}.bin`,
        bytes: Uint8Array.from(project.tiles.map((tile) => tile.characterIndexes[offset] ?? 0)),
      });
    }
  }
  return files;
}

export function exportProjectJson(project: ProjectData): string {
  return JSON.stringify(project, null, 2);
}

export function importProjectJson(text: string): ProjectData {
  return JSON.parse(text) as ProjectData;
}

function formatHexArray(bytes: Uint8Array, indent = '  '): string {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = Array.from(bytes.slice(i, i + 16), (byte) => `0x${byte.toString(16).padStart(2, '0')}`);
    lines.push(`${indent}${chunk.join(', ')}${i + 16 < bytes.length ? ',' : ''}`);
  }
  return lines.join('\n');
}

function cArray(name: string, bytes: Uint8Array): string {
  return `// ${name}: ${bytes.length} bytes\nunsigned char ${name}[${bytes.length}] = {\n${formatHexArray(bytes)}\n};`;
}

export function exportOscar64Header(project: ProjectData): string {
  const pieces = [
    '/* Generated by C64 Multicolour Charset Editor. */',
    '/* Colour RAM is per screen cell; characterColourRamBytes uses each character default visible colour + 8. */',
    cArray('charsetData', exportCharsetBinary(project)),
    cArray('characterVisibleColours', exportCharacterVisibleColours(project)),
    cArray('characterColourRamBytes', exportCharacterColourRamBytes(project)),
    cArray('tileMapFlat', exportTilesFlat(project)),
  ];

  for (const file of exportTilesSeparated(project)) {
    const name = file.filename.replace('.bin', '').replace(/[^a-zA-Z0-9_]/g, '_');
    pieces.push(cArray(`tilePlane_${name.replace(/^tile_/, '')}`, file.bytes));
  }

  pieces.push(`// tile count: ${TILE_COUNT}, character count: ${CHARACTER_COUNT}, tile size: ${project.tileWidth}x${project.tileHeight}`);
  return `${pieces.join('\n\n')}\n`;
}
